apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  selector:
    matchLabels:
      app: todotrek
  template:
    metadata:
      labels:
        app: todotrek
    spec:
      containers:
      - name: todotrek
        image: todotrek_app:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
