apiVersion: apps/v1
kind: Deployment
metadata:
  name: todotrek-deployment
  labels:
    app: todotrek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todotrek
  template:
    metadata:
      labels:
        app: todotrek
    spec:
      containers:
      - name: todotrek
        image: todotrek_app
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
